# Generated by Django 5.2 on 2025-06-23 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('business', '0002_initial'),
        ('roles', '0002_mainrole_mainrolepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='business.business', verbose_name='Negocio activo actual'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_business_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='roles.businessrole', verbose_name='Rol actual de negocio'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='roles.mainrole', verbose_name='Rol principal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('client', 'Cliente'), ('business_owner', 'Propietario de Negocio')], default='client', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
