# Generated by Django 5.2 on 2025-04-16 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del rol')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_default', models.BooleanField(default=False, verbose_name='Es rol predeterminado')),
                ('can_modify', models.BooleanField(default=True, verbose_name='Se puede modificar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_roles', to='business.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Rol de negocio',
                'verbose_name_plural': 'Roles de negocio',
                'ordering': ['business', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_dashboard', models.BooleanField(default=False, verbose_name='Puede ver dashboard')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Puede gestionar usuarios')),
                ('can_manage_roles', models.BooleanField(default=False, verbose_name='Puede gestionar roles')),
                ('can_view_orders', models.BooleanField(default=False, verbose_name='Puede ver pedidos')),
                ('can_create_orders', models.BooleanField(default=False, verbose_name='Puede crear pedidos')),
                ('can_update_orders', models.BooleanField(default=False, verbose_name='Puede actualizar pedidos')),
                ('can_delete_orders', models.BooleanField(default=False, verbose_name='Puede eliminar pedidos')),
                ('can_view_inventory', models.BooleanField(default=False, verbose_name='Puede ver inventario')),
                ('can_manage_inventory', models.BooleanField(default=False, verbose_name='Puede gestionar inventario')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Puede ver reportes')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='Puede exportar datos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('business_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='roles.businessrole', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de roles',
            },
        ),
    ]
