# Generated by Django 5.2 on 2025-07-14 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('client', 'Cliente'), ('business_owner', 'Propietario de Negocio')], max_length=50, unique=True, verbose_name='Nombre del rol')),
                ('display_name', models.CharField(max_length=100, verbose_name='Nombre para mostrar')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Rol principal',
                'verbose_name_plural': 'Roles principales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_business', models.BooleanField(default=False, verbose_name='Puede crear negocios')),
                ('can_manage_own_businesses', models.BooleanField(default=False, verbose_name='Puede gestionar sus negocios')),
                ('can_create_posts', models.BooleanField(default=True, verbose_name='Puede crear publicaciones')),
                ('can_comment_posts', models.BooleanField(default=True, verbose_name='Puede comentar publicaciones')),
                ('can_like_posts', models.BooleanField(default=True, verbose_name='Puede dar me gusta')),
                ('can_follow_businesses', models.BooleanField(default=True, verbose_name='Puede seguir negocios')),
                ('can_view_business_profiles', models.BooleanField(default=True, verbose_name='Puede ver perfiles de negocios')),
                ('can_moderate_content', models.BooleanField(default=False, verbose_name='Puede moderar contenido')),
                ('can_access_admin_panel', models.BooleanField(default=False, verbose_name='Puede acceder al panel admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('main_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='roles.mainrole', verbose_name='Rol principal')),
            ],
            options={
                'verbose_name': 'Permisos de rol principal',
                'verbose_name_plural': 'Permisos de roles principales',
            },
        ),
    ]
