# Generated by Django 5.2 on 2025-06-17 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_initial_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_logout_time', models.IntegerField(default=30, help_text='Tiempo en minutos para cerrar sesión automáticamente', verbose_name='Tiempo de auto logout (minutos)')),
                ('session_timeout', models.IntegerField(default=60, help_text='Tiempo máximo de sesión en minutos', verbose_name='Timeout de sesión (minutos)')),
                ('require_two_factor', models.BooleanField(default=False, verbose_name='Requiere autenticación de dos factores')),
                ('allow_customer_registration', models.BooleanField(default=True, verbose_name='Permitir registro de clientes')),
                ('require_order_confirmation', models.BooleanField(default=True, verbose_name='Requerir confirmación de pedidos')),
                ('enable_table_service', models.BooleanField(default=True, verbose_name='Habilitar servicio de mesa')),
                ('enable_takeaway', models.BooleanField(default=True, verbose_name='Habilitar para llevar')),
                ('enable_delivery', models.BooleanField(default=False, verbose_name='Habilitar delivery')),
                ('low_stock_threshold', models.IntegerField(default=5, help_text='Cantidad mínima para alertas de stock bajo', verbose_name='Umbral de stock bajo')),
                ('auto_deduct_inventory', models.BooleanField(default=True, verbose_name='Deducir inventario automáticamente')),
                ('daily_report_time', models.TimeField(blank=True, help_text='Hora para envío de reporte diario', null=True, verbose_name='Hora de reporte diario')),
                ('weekly_report_day', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')], default=1, verbose_name='Día de reporte semanal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_settings', to='business.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Configuración de Negocio',
                'verbose_name_plural': 'Configuraciones de Negocio',
                'db_table': 'settings_business_settings',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Oscuro'), ('auto', 'Automático')], default='light', max_length=20, verbose_name='Tema')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=10, verbose_name='Idioma')),
                ('font_size', models.CharField(choices=[('small', 'Pequeño'), ('medium', 'Mediano'), ('large', 'Grande')], default='medium', max_length=20, verbose_name='Tamaño de fuente')),
                ('compact_mode', models.BooleanField(default=False, verbose_name='Modo compacto')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notificaciones habilitadas')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificaciones por email')),
                ('order_updates', models.BooleanField(default=True, verbose_name='Actualizaciones de pedidos')),
                ('inventory_alerts', models.BooleanField(default=True, verbose_name='Alertas de inventario')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='Notificaciones del sistema')),
                ('profile_visible', models.BooleanField(default=True, verbose_name='Perfil visible')),
                ('show_activity', models.BooleanField(default=False, verbose_name='Mostrar actividad')),
                ('allow_messages', models.BooleanField(default=True, verbose_name='Permitir mensajes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuario',
                'db_table': 'settings_user_settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Pedido creado'), ('order_confirmed', 'Pedido confirmado'), ('order_ready', 'Pedido listo'), ('order_delivered', 'Pedido entregado'), ('low_stock', 'Stock bajo'), ('user_joined', 'Usuario se unió'), ('daily_report', 'Reporte diario')], max_length=50, verbose_name='Tipo de notificación')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='business.business')),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificación',
                'db_table': 'settings_notification_template',
                'unique_together': {('business', 'notification_type')},
            },
        ),
    ]
