# Generated by Django 5.2 on 2025-07-06 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Negocio'), ('promotion', 'Promoción'), ('announcement', 'Anuncio')], default='personal', max_length=20, verbose_name='Tipo de publicación')),
                ('content', models.TextField(blank=True, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Imagen')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/', verbose_name='Video')),
                ('likes_count', models.IntegerField(default=0, verbose_name='Número de likes')),
                ('comments_count', models.IntegerField(default=0, verbose_name='Número de comentarios')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Fijado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(blank=True, help_text='Negocio desde el cual se publica (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='business.business')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Me gusta',
                'verbose_name_plural': 'Me gustas',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
