# Generated by Django 5.2 on 2025-06-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'Me gusta', 'verbose_name_plural': 'Me gustas'},
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Fijado'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Negocio'), ('promotion', 'Promoción'), ('announcement', 'Anuncio')], default='personal', max_length=20, verbose_name='Tipo de publicación'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Negocio desde el cual se publica (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='business.business'),
        ),
    ]
