# Generated by Django 5.2 on 2025-06-23 04:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Número de orden')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('preparing', 'Preparando'), ('ready', 'Lista'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('order_type', models.CharField(choices=[('dine_in', 'Para comer aquí'), ('takeaway', 'Para llevar'), ('delivery', 'Domicilio')], default='dine_in', max_length=20, verbose_name='Tipo de orden')),
                ('table_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de mesa')),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del cliente')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Dirección de entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Impuestos')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo de domicilio')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('estimated_preparation_time', models.DurationField(blank=True, null=True, verbose_name='Tiempo estimado de preparación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Listo')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregado')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado')),
                ('customer_notes', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('kitchen_notes', models.TextField(blank=True, verbose_name='Notas de cocina')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='business.business', verbose_name='Negocio')),
                ('chef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chef_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cocinero')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_orders', to=settings.AUTH_USER_MODEL, verbose_name='Mesero')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('product_description', models.TextField(blank=True, verbose_name='Descripción')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('modifications', models.TextField(blank=True, help_text='Ej: Sin cebolla, extra queso', verbose_name='Modificaciones')),
                ('cooking_instructions', models.TextField(blank=True, verbose_name='Instrucciones de cocina')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('preparing', 'Preparando'), ('ready', 'Lista'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Estado del item')),
                ('started_cooking_at', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de cocción')),
                ('finished_cooking_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de cocción')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Item de orden',
                'verbose_name_plural': 'Items de orden',
            },
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(choices=[('status_change', 'Cambio de estado'), ('assignment', 'Asignación'), ('delay', 'Retraso'), ('ready', 'Listo'), ('urgent', 'Urgente')], max_length=50, verbose_name='Tipo')),
                ('target_roles', models.JSONField(default=list, help_text='Lista de roles que deben recibir esta notificación', verbose_name='Roles objetivo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Enviada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('preparing', 'Preparando'), ('ready', 'Lista'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], max_length=20, verbose_name='Estado anterior')),
                ('new_status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('preparing', 'Preparando'), ('ready', 'Lista'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], max_length=20, verbose_name='Nuevo estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historiales de estado',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['business', 'status'], name='orders_orde_busines_1a89b8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['waiter', 'status'], name='orders_orde_waiter__74becb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['chef', 'status'], name='orders_orde_chef_id_477bdc_idx'),
        ),
    ]
