# Generated by Django 5.2 on 2025-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pagado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('preparing', 'Preparando'), ('ready', 'Lista'), ('paid', 'Pagada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], db_index=True, default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('preparing', 'Preparando'), ('ready', 'Lista'), ('paid', 'Pagada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], default='pending', max_length=20, verbose_name='Estado del item'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('preparing', 'Preparando'), ('ready', 'Lista'), ('paid', 'Pagada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], max_length=20, verbose_name='Nuevo estado'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='old_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('preparing', 'Preparando'), ('ready', 'Lista'), ('paid', 'Pagada'), ('delivered', 'Entregada'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada')], max_length=20, verbose_name='Estado anterior'),
        ),
    ]
