# Generated by Django 5.2 on 2025-06-24 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_paid_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Creada'), ('updated', 'Actualizada'), ('status_changed', 'Estado cambiado'), ('assigned', 'Asignada'), ('item_added', 'Item agregado'), ('item_updated', 'Item actualizado'), ('item_removed', 'Item eliminado'), ('cancelled', 'Cancelada'), ('refunded', 'Reembolsada'), ('note_added', 'Nota agregada')], max_length=20, verbose_name='Acción')),
                ('old_values', models.JSONField(blank=True, help_text='Valores antes del cambio', null=True, verbose_name='Valores anteriores')),
                ('new_values', models.JSONField(blank=True, help_text='Valores después del cambio', null=True, verbose_name='Valores nuevos')),
                ('details', models.TextField(blank=True, help_text='Información adicional sobre la acción', verbose_name='Detalles')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.order', verbose_name='Orden')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['order', '-timestamp'], name='orders_orde_order_i_387fdd_idx'), models.Index(fields=['action', '-timestamp'], name='orders_orde_action_e94a5f_idx'), models.Index(fields=['user', '-timestamp'], name='orders_orde_user_id_ca55f0_idx')],
            },
        ),
    ]
