# Generated by Django 5.2 on 2025-04-15 03:59

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número de identificación')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Nombre de usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es superusuario')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último ingreso')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Foto de perfil')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nacionalidad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='auth_app_users_permissions', to='auth.permission', verbose_name='permisos de usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
                'permissions': [('change_user_role', 'Puede cambiar el rol de un usuario'), ('assign_to_business', 'Puede asignar usuarios a negocios')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/', verbose_name='Logo')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['-created_at'],
                'permissions': [('view_inactive_business', 'Puede ver negocios inactivos'), ('activate_business', 'Puede activar o desactivar negocios')],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='auth_app.business', verbose_name='Negocio'),
        ),
        migrations.CreateModel(
            name='BusinessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del rol')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_default', models.BooleanField(default=False, verbose_name='Es rol predeterminado')),
                ('can_modify', models.BooleanField(default=True, verbose_name='Se puede modificar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_roles', to='auth_app.business', verbose_name='Negocio')),
            ],
            options={
                'verbose_name': 'Rol de negocio',
                'verbose_name_plural': 'Roles de negocio',
                'ordering': ['business', 'name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='auth_app.businessrole', verbose_name='Rol de negocio'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_dashboard', models.BooleanField(default=False, verbose_name='Puede ver dashboard')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='Puede gestionar usuarios')),
                ('can_manage_roles', models.BooleanField(default=False, verbose_name='Puede gestionar roles')),
                ('can_view_orders', models.BooleanField(default=False, verbose_name='Puede ver pedidos')),
                ('can_create_orders', models.BooleanField(default=False, verbose_name='Puede crear pedidos')),
                ('can_update_orders', models.BooleanField(default=False, verbose_name='Puede actualizar pedidos')),
                ('can_delete_orders', models.BooleanField(default=False, verbose_name='Puede eliminar pedidos')),
                ('can_view_inventory', models.BooleanField(default=False, verbose_name='Puede ver inventario')),
                ('can_manage_inventory', models.BooleanField(default=False, verbose_name='Puede gestionar inventario')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='Puede ver reportes')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='Puede exportar datos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('business_role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='auth_app.businessrole', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de roles',
            },
        ),
    ]
